services:
  group-bet-logger:
    build:
      context: .
      target: development
    image: groupbetlogger
    command: >
      sh -c "
        scripts/wait-for/wait-for group-bet-logger-postgres:5432 --
        npm run migrate && npm start"
